version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: mydelivery-postgres
    environment:
      POSTGRES_DB: mydeliverydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mydelivery-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydeliverydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mydelivery-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: develop  # ‚Üê ATIVA O PROFILE
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - mydelivery-network

volumes:
  postgres-data:
    driver: local

networks:
  mydelivery-network:
    driver: bridge